### ISSUE TITLE
app resets R to default library

### ISSUE THREAD

**Issue by danmsf** [metrumresearchgroup/d3Tree#1]
Hi
Great blog, app and presentation. Hats off for all the work!!

Unfortunately running the app through the "shiny::runGitHub("metrumresearchgroup/SearchTree")" line in R on my comp resets the libPaths to be just the basic directory (i.e. "C:/Program Files/R/R-3.3.0/library") getting rid of my user\home directory where I keep all the packages....
Not sure but probably has something to do with setting .libPaths() to your directory instead of adding it to the list of directories...

**Comment by yonicd** [comment]
Yes. I see that. its built to run on our servers for the blog. i'll see how i can work around that

**Comment by yonicd** [comment]
I pushed a version of the app to run directly from github. you can try the call now from the repo.

**Comment by danmsf** [comment]
Works great! Thanks!
