### ISSUE TITLE
"_update" added at the end of Shiny input names

### ISSUE THREAD

**Issue by ncls33** [metrumresearchgroup/d3Tree#13]
First of all, thank you for your work on the amazing packages.

I’m new to shiny and I’m trying to develop an app using the d3tree package. I notice that to call some input id’s I have to add “_update” at the end (from some of the examples available in GitHub). Would you mind pointing me towards where I can learn when I should add _update or other suffixes to input ids in shiny?  I am at a loss as to when this should be the case and can’t find any guidance online.

Thank you!

Natalie

**Comment by yonicd** [comment]
Thanks for trying out the package!

The use case for the `*_update` functions are for when you want to "observe" what the user is clicking on in the widget (the tree) while shiny is running. 

This can be useful for have a different part of your application that is reactive to the current state of the tree. I have used d3Tree in the past as a filter of a complex data set where the user is filtering on columns and values based on which branches/leaves are open.

[Here](https://github.com/yonicd/d3Tree/tree/master/inst/examples/titanic_shiny) is an example application for that functionality, it is based on the titanic data. You can copy the files into your R session and run the app as is to get a feel for the functionality.

Breaking down the server file

In the `server.R` file a new `reactive` container object is created, you can think of it as another `intput` object like the one shiny has in every app, just you decide what does in there. shiny will respect that reactive object just like input.

```r
shinyServer(function(input, output, session) {
```
A `selectize` input object that holds the tree hierarchy (data columns)

```r
  output$Hierarchy <- renderUI({
    Hierarchy=names(m)
    Hierarchy=head(Hierarchy,-1)
    selectizeInput("Hierarchy","Tree Hierarchy",
                   choices = Hierarchy,multiple=T,selected = Hierarchy,
                   options=list(plugins=list('drag_drop','remove_button')))
  })
```

This is the new reactive object that we can populate

```r
  network <- reactiveValues()
```

we are telling shiny here to observe events of the selectize input Hierarchy, when it changes the D3 widget is updated and is invalidated.

The important part here is that we are putting it in `output$d3`, this is what shiny is seeing under the hood and appends the `*_update` to.

```r
  observeEvent(input$Hierarchy,{
    output$d3 <- renderD3tree({
      if(is.null(input$Hierarchy)){
        p=m
      }else{
        p=m%>%select(one_of(c(input$Hierarchy,"NEWCOL")))%>%unique
      }
      
      d3tree(data = list(root = df2tree(struct = p,rootname = 'Titanic'), layout = 'collapse'),
                  activeReturn = c('name','value','depth','id'),
                  height = 18)
    })
  })
```

This is waiting for changes to `d3_update`. inside that object is information about the current widget state

- `.nodesData` : the current nodes that are open in the tree
- `.activeNode`: if a node was clicked the index would be here.

We place this into the reactive container `network` so shiny will treat it as a reactive object just like `input`

```r
  observeEvent(input$d3_update,{
    network$nodes <- unlist(input$d3_update$.nodesData)
    activeNode<-input$d3_update$.activeNode
    if(!is.null(activeNode)) network$click <- jsonlite::fromJSON(activeNode)
  })
```

We observe the event of `network$click`, ie if a node was clicked and have a table be dependent on it.

```r

  observeEvent(network$click,{
    output$clickView<-renderTable({
      as.data.frame(network$click)
    },caption='Last Clicked Node',caption.placement='top')
  })
```
 
We observe the event of `network$nodes`, ie the current structure of the tree and convert it to a data.frame to use

```r
  TreeStruct=eventReactive(network$nodes,{
    df=m
    if(is.null(network$nodes)){
      df=m
    }else{
      
      x.filter=tree.filter(network$nodes,m)
      df=ddply(x.filter,.(ID),function(a.x){m%>%filter_(.dots = list(a.x$FILTER))%>%distinct})
    }
    df
  })
```

We use the reactive data.frame TreeStruct to output it to a table
```r
  output$table <- renderTable(expr = {
    TreeStruct()%>%select(-NEWCOL)
  })
```

```r
})
```

Hopefully this helps you get started. If you have more questions feel free to continue this issue with a comment.

**Comment by ncls33** [comment]
Thank so much you for the thoughtful and detailed response! This is very helpful.

**Comment by yonicd** [comment]
Great 👍. Closing this issue for now. Feel free to continue to post here if any new questions arise about the subject.
