### ISSUE TITLE
use data.tree or GeneralTree for better tree manipulation in R

### ISSUE THREAD

**Issue by timelyportfolio** [metrumresearchgroup/d3Tree#3]
As I started to write the convert the d3 tree back to R function, I realized that even when converted, it will be difficult to manipulate in R.  I thought [`data.tree`](https://github.com/gluc/data.tree) or [`GeneralTree`](https://github.com/abossenbroek/GeneralTree) might be more useful, but it mostly depends on how much tree manipulation you will need to accomplish and if you are ok with additional dependencies.

Either way, I will try to get a d3 json to `tibble` function finished by the end of the day.

**Comment by yonicd** [comment]
great. 

In this implementation i needed to do some manipulation to understand which siblings were clicked under each active parent. (which is most of the tree.filter function)

https://github.com/metrumresearchgroup/SearchTree/blob/master/www/functions/d3TreeFunctions.r#L56

thank you!

**Comment by yonicd** [comment]
Is there a way to query from R the d3 script and return a name vector of all objects that can returned and let the R user decide what they want to observe? that would be the best option (something like ellipses)
