### ISSUE TITLE
Vertical layout

### ISSUE THREAD

**Issue by sinacek** [metrumresearchgroup/d3Tree#7]
Hi,
thank you a lot for this shiny widget! I would like ask you if you have in plan add there option for vertical layout of tree? 
The second question is if can widget also return id or name of the last clicked node (collapsed/expanded)

Thanks a lot for response
Frantisek

**Comment by yonicd** [comment]
both options added.

  - New shiny observer 'activeNode' added to return meta data of last clicked node. (full example app see [here](https://raw.githubusercontent.com/metrumresearchgroup/d3Tree/master/inst/examples/titanic_shiny))
  
  Server Side
  
```
  observeEvent(input$d3_update,{
    activeNode<-input$d3_update$.activeNode
    if(!is.null(activeNode)) network$click <- jsonlite::fromJSON(activeNode)
  })
  
  observeEvent(network$click,{
    output$clickView<-renderTable({
      as.data.frame(network$click)
    },caption='Last Clicked Node',caption.placement='top')
  })
  
```
  
  UI Side
  
```
  tableOutput("clickView")
```
  
  - give option to grow a horizontal tree (default) and a vertical tree
  

```
    #horizontal(default)
    d3tree(list(root = df2tree(rootname = 'Titanic',struct = as.data.frame(Titanic),toolTip = letters[1:5]),
    layout = 'collapse'))
    
    #vertical
    d3tree(list(root = df2tree(rootname = 'Titanic',struct = as.data.frame(Titanic),toolTip = letters[1:5]),
    layout = 'collapse'),direction = 'v')
    
```

**Comment by sinacek** [comment]
Link https://raw.githubusercontent.com/metrumresearchgroup/d3Tree/master/inst/examples/titanic_shiny doesn't work :/

**Comment by yonicd** [comment]
ha. woops

https://github.com/metrumresearchgroup/d3Tree/tree/master/inst/examples/titanic_shiny
