### ISSUE TITLE
Allow add other values to node

### ISSUE THREAD

**Issue by sinacek** [metrumresearchgroup/d3Tree#8]
Hi,
I tried new feature from https://github.com/metrumresearchgroup/d3Tree/issues/7 for use last clicked node. That gave me an idea, that I would like to know, which node it is by their id. I can set new attribute in R list structure and it is propagate to JS nodes, but for active node is returned just value and name.
I suggest return all node properties (activeNode=d;) because we don't know which other attributes we will use next time. What do you think about that?

**Comment by yonicd** [comment]
Not sure what the application of that would be. Can you give an example?

**Comment by sinacek** [comment]
I would like print detail about the node in separate table. For this purpose I need to know id of that node.

**Comment by yonicd** [comment]
`activeReturn` is an argument to access any string or numeric attribute in the `d`, which shiny will observe.

notice that the id index starts from the bottom of each level.

```
d3tree(list(root = df2tree(rootname = 'Titanic',
struct = as.data.frame(Titanic),
toolTip = letters[1:5]),layout = 'collapse'),
activeReturn = c('name','value','depth','id') #<----
)
```

**Comment by sinacek** [comment]
ok, thanks
