### ISSUE TITLE
interactive app page can't be found

### ISSUE THREAD

**Issue by liangjune** [metrumresearchgroup/d3Tree#9]
I am interested in interactive app but page can't be found T.T
tinyurl.com/zaf2gm8  (http://metrumrg.com/blog/2016/10/reactive-shiny-d3js-trees.html)

any other url for this shiny app? or ui & server code,

thanks a lot

**Comment by yonicd** [comment]
unfortunately that app was removed from our servers by accident. we will try to host it on another server and update the post appropriately.

**Comment by yonicd** [comment]
sorry for the delay. you can find an interactive app [here](https://metrumrg.shinyapps.io/d3Tree/)
